# Generated by Django 4.2.7 on 2023-11-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0003_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='detail',
            new_name='comment',
        ),
    ]
