# Generated by Django 4.2.7 on 2023-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0004_alter_comment_options_rename_detail_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='imgs/'),
        ),
    ]
