# Generated by Django 4.2.7 on 2023-11-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0005_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
