# Generated by Django 4.2.7 on 2023-11-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0007_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
