# Generated by Django 4.2.7 on 2023-11-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0008_rename_title_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
